title: "Tianjiao Luo"
author: "Blog Author"
description: "Tsinghua University \n University of California, Berkeley"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "cv.pdf", title: "CV", icon = Home}
  - {title: "LinkedIn", url: "https://www.linkedin.com/in/tianjiao-luo-99a60bba/"}
  - {title: "Lab", url: "https://ml.cs.tsinghua.edu.cn/"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "t.luo@berkeley.edu"}
  - {title: Github, icon: github, url: "https://github.com/TianjiaoLuo"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
